const fs = require('fs');
let content = fs.readFileSync('src/components/IntensiveStudy.tsx', 'utf8');

content = content.replace(/if \(type === "Động từ nhóm I"\) {\s*return "text-\[10px\] font-bold   px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border    ";\s*}/g, 'if (type === "Động từ nhóm I") {\n    return "text-[10px] font-bold px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border bg-[var(--badge-blue-bg)] text-[var(--badge-blue-text)] border-[var(--badge-blue-border)]";\n  }');
content = content.replace(/else if \(type === "Động từ nhóm II"\) {\s*return "text-\[10px\] font-bold   px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border    ";\s*}/g, 'else if (type === "Động từ nhóm II") {\n    return "text-[10px] font-bold px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border bg-[var(--badge-purple-bg)] text-[var(--badge-purple-text)] border-[var(--badge-purple-border)]";\n  }');
content = content.replace(/else if \(type === "Động từ nhóm III"\) {\s*return "text-\[10px\] font-bold   px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border    ";\s*}/g, 'else if (type === "Động từ nhóm III") {\n    return "text-[10px] font-bold px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border bg-[var(--badge-pink-bg)] text-[var(--badge-pink-text)] border-[var(--badge-pink-border)]";\n  }');
content = content.replace(/else if \(type === "Danh từ"\) {\s*return "text-\[10px\] font-bold   px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border    ";\s*}/g, 'else if (type === "Danh từ") {\n    return "text-[10px] font-bold px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border bg-[var(--badge-emerald-bg)] text-[var(--badge-emerald-text)] border-[var(--badge-emerald-border)]";\n  }');
content = content.replace(/else if \(type === "Tính từ đuôi-i" \|\| type === "Tính từ i"\) {\s*return "text-\[10px\] font-bold   px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border    ";\s*}/g, 'else if (type === "Tính từ đuôi-i" || type === "Tính từ i") {\n    return "text-[10px] font-bold px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border bg-[var(--badge-amber-bg)] text-[var(--badge-amber-text)] border-[var(--badge-amber-border)]";\n  }');
content = content.replace(/else if \(type === "Tính từ đuôi-na" \|\| type === "Tính từ na"\) {\s*return "text-\[10px\] font-bold   px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border    ";\s*}/g, 'else if (type === "Tính từ đuôi-na" || type === "Tính từ na") {\n    return "text-[10px] font-bold px-2 py-1 uppercase tracking-wider whitespace-nowrap rounded-sm border bg-[var(--badge-orange-bg)] text-[var(--badge-orange-text)] border-[var(--badge-orange-border)]";\n  }');

fs.writeFileSync('src/components/IntensiveStudy.tsx', content);
